/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class StubDriverCreator : DriverCreator {
  private HandleRef swigCPtr;

  internal StubDriverCreator(IntPtr cPtr, bool cMemoryOwn) : base(yarpPINVOKE.StubDriverCreator_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(StubDriverCreator obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~StubDriverCreator() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          yarpPINVOKE.delete_StubDriverCreator(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public StubDriverCreator(string name, string wrap, string code, string libname) : this(yarpPINVOKE.new_StubDriverCreator(name, wrap, code, libname), true) {
  }

  public new ConstString toString() {
    ConstString ret = new ConstString(yarpPINVOKE.StubDriverCreator_toString(swigCPtr), true);
    return ret;
  }

  public override ConstString getName() {
    ConstString ret = new ConstString(yarpPINVOKE.StubDriverCreator_getName(swigCPtr), true);
    return ret;
  }

  public override ConstString getWrapper() {
    ConstString ret = new ConstString(yarpPINVOKE.StubDriverCreator_getWrapper(swigCPtr), true);
    return ret;
  }

  public override ConstString getCode() {
    ConstString ret = new ConstString(yarpPINVOKE.StubDriverCreator_getCode(swigCPtr), true);
    return ret;
  }

  public override DeviceDriver create() {
    IntPtr cPtr = yarpPINVOKE.StubDriverCreator_create(swigCPtr);
    DeviceDriver ret = (cPtr == IntPtr.Zero) ? null : new DeviceDriver(cPtr, false);
    return ret;
  }

}
